# Generated by Django 4.2.8 on 2023-12-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=99)),
                ('rank', models.CharField(blank=True, max_length=39)),
                ('job', models.CharField(blank=True, max_length=199)),
            ],
        ),
    ]
