# Generated by Django 4.2.8 on 2023-12-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Armia', '0003_enginirytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryBase',
            fields=[
                ('location', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='enginirytype',
            name='name',
            field=models.CharField(max_length=98),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('ammo_amount', models.IntegerField()),
                ('military_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Armia.weaponmodel')),
            ],
        ),
    ]
