# Generated by Django 4.2.8 on 2023-12-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Armia', '0006_rename_location_militarybase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='military_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.weaponmodel'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='job',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.weaponmodel'),
        ),
        migrations.CreateModel(
            name='Enginiry',
            fields=[
                ('function', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enginiry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.enginirytype')),
                ('military_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase')),
            ],
        ),
        migrations.CreateModel(
            name='BaseCodes',
            fields=[
                ('base_cipher', models.IntegerField(primary_key=True, serialize=False)),
                ('id_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('base_cipher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.basecodes')),
            ],
        ),
        migrations.AddField(
            model_name='soldier',
            name='enginiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.enginiry'),
        ),
    ]
