# Generated by Django 4.2.8 on 2023-12-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Armia', '0007_soldier_military_base_soldier_weapon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecodes',
            old_name='base_cipher',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='basecodes',
            old_name='id_base',
            new_name='military_base',
        ),
        migrations.AlterField(
            model_name='soldier',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.weapon'),
        ),
    ]
