# Generated by Django 4.2.8 on 2023-12-18 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Armia', '0008_rename_base_cipher_basecodes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='base_cipher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.basecodes', verbose_name='Код базы'),
        ),
        migrations.AlterField(
            model_name='army',
            name='country',
            field=models.CharField(max_length=40, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='army',
            name='type',
            field=models.CharField(max_length=40, verbose_name='Тип армии'),
        ),
        migrations.AlterField(
            model_name='basecodes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='basecodes',
            name='military_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase', verbose_name='Военная база'),
        ),
        migrations.AlterField(
            model_name='enginiry',
            name='enginiry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.enginirytype', verbose_name='Тип инженерии'),
        ),
        migrations.AlterField(
            model_name='enginiry',
            name='function',
            field=models.CharField(max_length=200, verbose_name='Функция'),
        ),
        migrations.AlterField(
            model_name='enginiry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='enginiry',
            name='military_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase', verbose_name='Военная база'),
        ),
        migrations.AlterField(
            model_name='enginirytype',
            name='name',
            field=models.CharField(max_length=98, verbose_name='Тип инженерии'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='base_type',
            field=models.CharField(max_length=30, verbose_name='Тип базы'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='enginiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.enginiry', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='full_name',
            field=models.CharField(max_length=99, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='job',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='military_base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase', verbose_name='Военная база'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(max_length=40, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.weapon', verbose_name='Оружие'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammo_amount',
            field=models.IntegerField(verbose_name='Количество боезапаса'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='military_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armia.militarybase', verbose_name='Военная база'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Armia.weaponmodel', verbose_name='Модель оружия'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип оружия'),
        ),
        migrations.AlterField(
            model_name='weaponmodel',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Название модели'),
        ),
    ]
